name: next_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  razorpay_flutter: ^1.3.5
  universal_html: ^2.2.4

  supabase_flutter: ^2.3.4

  

  # UI & Utility Packages
  jwt_decoder: ^2.0.1
  like_button: ^2.0.5
  table_calendar: ^3.0.9
  url_launcher: ^6.2.5
  app_links: ^3.4.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  sign_in_with_apple: ^6.1.0
  timeago: ^3.0.2
  font_awesome_flutter: ^10.5.0
  realtime_client: ^2.5.0
  http: ^1.2.1
  fluttertoast: ^8.2.12
  confetti: ^0.7.0
  
  fl_chart: ^0.64.0


  # Image Picker
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.24.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/Favicon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/img/Favicon.png"
    background_color: "#hex_code"
    theme_color: "#hex_code"


flutter:
  uses-material-design: true

  assets:
    - assets/img/Icon.png
    - assets/img/Favicon.png
    - assets/img/Adaptive-icon.png
    - assets/img/default_avatar.png
